### ISSUE TITLE
Dependency rdrop2 for crossmeta error

### ISSUE THREAD

**Issue by harshameghadri** [alexvpickering/crossmeta#10]
Hello Alex,

I would like to use your ccmap package and one of the libs that is also required (as seen in the [instructions](https://bioconductor.org/packages/release/bioc/vignettes/ccmap/inst/doc/ccmap-vignette.html)) is crossmeta. I see that cross meta requires rdrop2 as a dependency.
- Rdrop2 is not available anymore for R 4.0.2

> Installing package into ‘/path/to/lib/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rdrop2’ is not available (for R version 4.0.2)
Warning in install.packages :
  converting NULL pointer to R NULL

Is there a workaround for this? 

Best Wishes,
Harsha

**Comment by alexvpickering** [comment]
Hi Harsha,

I've removed the `rdrop2` dependency. Please go ahead and try to install the latest version with:

```R
install.packages('remotes')
remotes::install_github('alexvpickering/crossmeta')
```

**Comment by harshameghadri** [comment]
Thanks Alex, It works now.
