### ISSUE TITLE
es_meta || how to begin with external differential gene expression data

### ISSUE THREAD

**Issue by complexgenome** [alexvpickering/crossmeta#7]
hi,
Thanks for this awesome tool. 

I'm interested to use crossmeta to perform meta analysis for two studies that have differential gene expression data available.
I've column with log fold-change, symbol/ensembl id, p-value, adjusted p-value.

I'd be interested to know how to begin or apply es_meta to my data. The vignettes and manual assume that data need to be processed and then outcome from the `diff_expr` will be used.

http://bioconductor.org/packages/devel/bioc/vignettes/crossmeta/inst/doc/crossmeta-vignette.html

https://www.bioconductor.org/packages/devel/bioc/manuals/crossmeta/man/crossmeta.pdf

**Comment by alexvpickering** [comment]
Hi @sariya,

Yes the tool currently requires processing through `crossmeta` because the the differential expression analysis uses intermediate values from `limma` differential expression analysis. Specifically, `crossmeta` uses standardised effect size values (dprimes) calculated from the sample size and degrees of freedom.

You could look into the `metap` package and perform a p-value based meta analysis with your results.

**Comment by complexgenome** [comment]
hi alex,
Thanks for the library. I'm not looking for library that combines p-value based on different statistical methods: inverse, fisher; rather that takes into consideration lofFc, P-value when data with differential gene expression are present.

Would be great to create this feature in your library?

**Comment by alexvpickering** [comment]
I think this is outside the scope of the package which is for end-to-end meta-analyses of public microarray data.

I am not aware of a logFC/pvalue based meta-analysis but this could very well exist and would be useful for cases as you describe. I would just implement it as a seperate package. Best,

**Comment by complexgenome** [comment]
I understand. There are tools (MetaVolcanoR) that take into log fold change. 

I was exploring other tools such as crossmeta. Would be cool to work together on something like this if you've bandwidth. I've very limited experience in R package development. 
 
Thank you.

**Comment by alexvpickering** [comment]
No worries - why not just use MetaVolcanoR?

**Comment by complexgenome** [comment]
I'm running into errors there, so :-| 
have asked dev for the error, let us see :)
